#!/usr/bin/env python3
# GeneralsX @feature cemlyn007 28/09/2026 Guards the upstream singleton declarations for RTS_ENGINE_CONTEXT
# (PLAN-023 Phase 1)
#
# With the CMake option RTS_ENGINE_CONTEXT on, every singleton listed in
# Core/GameEngine/Include/Common/EngineSingletons.inl is a field of rts::EngineContext, and `TheXxx` is a
# macro (Core/GameEngine/Include/Common/EngineSingletonMacros.h, generated by this script). The upstream
# `extern Xxx *TheXxx;` declarations and `Xxx *TheXxx = nullptr;` definitions must then disappear, or they
# would expand to `extern Xxx *(::rts::ctx()->TheXxx_);`. Rather than edit those lines (every weekly upstream
# merge would conflict with the edit), this script wraps each one in
#
#     #if !RTS_ENGINE_CONTEXT
#     extern Xxx *TheXxx;
#     #endif
#
# which only adds lines, so merges stay clean. It is idempotent: rerun it after an upstream sync, or after
# adding a name to EngineSingletons.inl.
#
# Usage (from the GeneralsX root, or with --root):
#   engine_context_guards.py guard   regenerate the macro header and add any missing guards
#   engine_context_guards.py check   exit 1 if the macro header is stale, a listed name has an unguarded
#                                    extern or definition, or an `extern ... TheXxx;` names a singleton that
#                                    is neither listed nor classified below (so a new upstream singleton
#                                    cannot slip in as a silently shared global)
#   engine_context_guards.py list    print every `extern ... TheXxx;` line with its classification
#
# Scope: Core and GeneralsMD/Code, without their Tools directories (the tools are excluded from
# RTS_ENGINE_CONTEXT builds, see cmake/config-build.cmake). The Generals base game is not guarded yet
# (PLAN-023's Generals backport).

import argparse
import os
import re
import sys

SCAN_ROOTS = ["Core", "GeneralsMD/Code"]
SKIP_DIRS = {"Core/Tools", "GeneralsMD/Code/Tools"}
SOURCE_EXTENSIONS = (".h", ".hpp", ".inl", ".cpp")

SINGLETON_LIST = "Core/GameEngine/Include/Common/EngineSingletons.inl"
MACRO_HEADER = "Core/GameEngine/Include/Common/EngineSingletonMacros.h"

GUARD_OPEN = "#if !RTS_ENGINE_CONTEXT"
GUARD_CLOSE = "#endif"

# `extern ... TheXxx;` names that are deliberately NOT per engine. Each one stays an ordinary global. The
# check fails on any `extern ... TheXxx;` that is neither in EngineSingletons.inl nor here.
PROCESS_GLOBAL = {
    # Process-wide by design (PLAN-023 Phase 1).
    "TheAsciiStringCriticalSection": "critical section, process-wide lock",
    "TheUnicodeStringCriticalSection": "critical section, process-wide lock",
    "TheDmaCriticalSection": "critical section, process-wide lock",
    "TheMemoryPoolCriticalSection": "critical section, process-wide lock",
    "TheDebugLogCriticalSection": "critical section, process-wide lock",
    "TheCritSecPerfGather": "critical-section profiling, process-wide",
    "TheMemoryPoolFactory": "memory manager, process-wide",
    "TheDynamicMemoryAllocator": "memory manager, process-wide",
    "TheNameKeyGenerator": "shared immortal NameKey generator (PLAN-023 Decision 2)",
    "TheVersion": "build version, identical for every engine",
    "TheSystemIsUnicode": "process-global const",
    # Debug-only globals.
    "TheCurrentIgnoreCrashPtr": "debug",
    "TheCRCFirstFrameToLog": "debug (CRC logging window)",
    "TheCRCLastFrameToLog": "debug (CRC logging window)",
    "TheDebugIgnoreSyncErrors": "debug",
    "TheObjectIDToDebug": "debug",
    "TheMiniDumper": "crash dumps, process-wide (Windows)",
    # Process-level host objects: one window and one Win32 message pump per process.
    "TheSDL3Window": "the game's SDL window: with RTS_ENGINE_CONTEXT the engine's own (EngineContext::sdl3Window, Common/ApplicationWindow.h; PLAN-023 Phase 8, stage RR2a-2), this extern is the build without it",
    "TheWin32Mouse": "Windows WndProc mouse (WinMain only)",
    # Dead online back ends, stubbed or unused on Linux/macOS.
    "TheWebBrowser": "WOL browser, a stub off Windows (CComObject<WebBrowser> on Windows)",
    "TheGPConnection": "GameSpy GP, not compiled",
    "TheGameSpyMutex": "GameSpy thread mutex object",
    "TheLobbyQueuedUTMs": "GameSpy lobby menu queue (menu state; one UI engine per process)",
    # Not pointers: objects and values that later phases classify (the Phase 1 nm classification).
    "TheDX8MeshRenderer": "W3D mesh renderer object of the build without the context; with it, a PER_ENGINE_STATIC (PLAN-023 Phase 3)",
    "TheW3DFrameLengthInMsec": "W3D frame timing value: every engine writes the same constant (GameClient::init sets MSEC_PER_LOGICFRAME_REAL); the unsynchronized write matters only with threads",
    "TheWaterTransparency": "OVERRIDE<> INI object of the build without the context; with it, a PER_ENGINE_STATIC (PLAN-023 Phase 3)",
    "TheWeatherSetting": "OVERRIDE<> INI object of the build without the context; with it, a PER_ENGINE_STATIC (PLAN-023 Phase 3)",
    "TheSupplyAndTechImageLocations": "skirmish-menu object (PLAN-023 Phase 4)",
    "TheThingTemplateBeingParsedName": "INI parse scratch string (PLAN-023 Phase 4)",
    "TheSkateDistOverride": "INI parse scratch value (PLAN-023 Phase 4)",
    "TheMousePos": "window mouse position (PLAN-023 Phase 8, render mode)",
    "TheMessageTime": "Windows message time (WinMain only)",
    "TheGameSpyThread": "GameSpy thread object",
    "TheDebugLevels": "debug",
}

# Constant tables (`TheXxxNames`, field-parse tables, lookup lists): process-global, never written.
CONSTANT_TABLE_RE = re.compile(r"(Names|FieldParse|FieldParseTable|LookupList)$")


# A PER_ENGINE_STATIC's static (`TheXxx_perEngine`, rts::PerEngineStatic<T>): it holds only the slot index,
# allocated at static initialisation (file or class scope) or at the first call (function-local); the object lives in each engine's EngineContext.
PER_ENGINE_STATIC_RE = re.compile(r"_perEngine$")


def process_global_reason(name):
    if name in PROCESS_GLOBAL:
        return PROCESS_GLOBAL[name]
    if PER_ENGINE_STATIC_RE.search(name):
        return "PER_ENGINE_STATIC slot index; the object is per engine"
    if CONSTANT_TABLE_RE.search(name):
        return "constant table"
    return None


EXTERN_RE = re.compile(r'^\s*extern\s+(?!"C")[^()=;]*?\b(The[A-Z]\w*)\s*(?:\[[^\]]*\])?\s*;')
DEFINITION_RE = re.compile(
    r"^(?:/\*extern\*/\s*)?(?:class\s+|struct\s+)?[A-Za-z_][\w:<>]*\s*\*\s*(The[A-Z]\w*)\s*(?:=\s*[^;]*)?;"
)
ENTRY_RE = re.compile(r"^\s*RTS_ENGINE_SINGLETON(_STRUCT|_ZH)?\(\s*([\w:]+)\s*,\s*(\w+)\s*\)\s*$")

PREPROCESSOR_RE = re.compile(r"^\s*#\s*(if|ifdef|ifndef|elif|else|endif)\b")
IF_RE = re.compile(r"^\s*#\s*if(?:def|ndef)?\b")
ENDIF_RE = re.compile(r"^\s*#\s*endif\b")


def read_singleton_list(root):
    """The listed names, and the list's entries for the macro header (plain or Zero Hour only)."""
    names = []
    lines = []
    with open(os.path.join(root, SINGLETON_LIST), encoding="latin-1") as f:
        for raw in f:
            line = raw.rstrip("\r\n")
            entry = ENTRY_RE.match(line)
            if entry:
                names.append(entry.group(3))
                lines.append(("entry_zh" if entry.group(1) == "_ZH" else "entry", entry.group(3)))
            elif PREPROCESSOR_RE.match(line):
                # A conditional would give rts::EngineContext a different layout per game or library.
                sys.exit(
                    f"{SINGLETON_LIST}: `{line.strip()}`: no conditionals in the list; a Zero Hour-only "
                    "singleton is RTS_ENGINE_SINGLETON_ZH (a field in both games, see the list's header)"
                )
    if len(set(names)) != len(names):
        dupes = sorted({n for n in names if names.count(n) > 1})
        sys.exit(f"{SINGLETON_LIST}: duplicate entries: {', '.join(dupes)}")
    return names, lines


def render_macro_header(lines):
    out = [
        "// FILE: EngineSingletonMacros.h",
        "// GeneralsX @feature cemlyn007 28/09/2026 GENERATED by scripts/cpp/engine_context_guards.py from",
        "// EngineSingletons.inl: do not edit. Included by Common/EngineContext.h (RTS_ENGINE_CONTEXT only).",
        "#pragma once",
        "",
    ]
    for kind, value in lines:
        define = f"#define {value} (::rts::ctx()->{value}_)"
        if kind == "entry_zh":
            out.extend(["#if RTS_ZEROHOUR", define, "#endif"])
        else:
            out.append(define)
    return "\n".join(out) + "\n"


def source_files(root):
    for scan_root in SCAN_ROOTS:
        for dirpath, dirnames, filenames in os.walk(os.path.join(root, scan_root)):
            rel = os.path.relpath(dirpath, root).replace(os.sep, "/")
            dirnames[:] = sorted(
                d for d in dirnames if f"{rel}/{d}" not in SKIP_DIRS
            )
            for filename in sorted(filenames):
                if filename.endswith(SOURCE_EXTENSIONS):
                    yield os.path.join(dirpath, filename)


def classify(line, is_cpp, listed):
    """('extern' | 'definition', name) for a line that declares or defines a singleton, else None."""
    extern = EXTERN_RE.match(line)
    if extern:
        return "extern", extern.group(1)
    if is_cpp and not line[:1].isspace():
        definition = DEFINITION_RE.match(line)
        if definition and definition.group(1) in listed:
            return "definition", definition.group(1)
    return None


def process_file(path, listed):
    """Returns (new text or None if unchanged, unguarded listed hits, unlisted extern hits)."""
    with open(path, "rb") as f:
        data = f.read()
    text = data.decode("latin-1")
    lines = text.splitlines(keepends=True)
    is_cpp = path.endswith(".cpp")

    out = []
    unguarded = []
    unlisted = []
    guard_depth = 0  # > 0 inside our own #if !RTS_ENGINE_CONTEXT block
    if_depth = 0
    pending = []  # consecutive lines that need a new guard

    def flush():
        if not pending:
            return
        ending = "\r\n" if pending[0].endswith("\r\n") else "\n"
        out.append(GUARD_OPEN + ending)
        out.extend(pending)
        last = pending[-1]
        if not last.endswith("\n"):
            out[-1] = last + ending
        out.append(GUARD_CLOSE + ending)
        pending.clear()

    for number, line in enumerate(lines, 1):
        stripped = line.rstrip("\r\n")
        if stripped.strip() == GUARD_OPEN:
            flush()
            if_depth += 1
            if guard_depth == 0:
                guard_depth = if_depth
            out.append(line)
            continue
        if IF_RE.match(stripped):
            flush()
            if_depth += 1
            out.append(line)
            continue
        if ENDIF_RE.match(stripped):
            flush()
            if guard_depth == if_depth:
                guard_depth = 0
            if_depth = max(0, if_depth - 1)
            out.append(line)
            continue

        hit = classify(stripped, is_cpp, listed)
        if hit is not None:
            kind, name = hit
            if name in listed:
                if guard_depth:
                    flush()
                    out.append(line)
                else:
                    unguarded.append((number, kind, name))
                    pending.append(line)
                continue
            if kind == "extern" and not guard_depth:
                unlisted.append((number, name, stripped.strip()))
        flush()
        out.append(line)
    flush()

    new_text = "".join(out)
    return (new_text if new_text != text else None), unguarded, unlisted


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=["guard", "check", "list"])
    parser.add_argument(
        "--root",
        default=os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")),
        help="GeneralsX source root (default: this script's repository)",
    )
    args = parser.parse_args()
    root = args.root

    names, list_lines = read_singleton_list(root)
    listed = set(names)
    overlap = listed & set(PROCESS_GLOBAL)
    if overlap:
        sys.exit(f"listed and process-global at once: {', '.join(sorted(overlap))}")

    problems = []

    header_path = os.path.join(root, MACRO_HEADER)
    header = render_macro_header(list_lines)
    try:
        with open(header_path, encoding="latin-1") as f:
            current_header = f.read()
    except FileNotFoundError:
        current_header = None
    if current_header != header:
        if args.mode == "guard":
            with open(header_path, "w", encoding="latin-1", newline="\n") as f:
                f.write(header)
            print(f"wrote {MACRO_HEADER}")
        elif args.mode == "check":
            problems.append(f"{MACRO_HEADER} is stale: run `{sys.argv[0]} guard`")

    guarded_names = set()
    changed = 0
    unknown = []
    for path in source_files(root):
        new_text, unguarded, unlisted = process_file(path, listed)
        rel = os.path.relpath(path, root)
        for number, kind, name in unguarded:
            guarded_names.add(name)
            if args.mode == "check":
                problems.append(f"{rel}:{number}: unguarded {kind} of {name}")
        for number, name, text in unlisted:
            if args.mode == "list":
                reason = process_global_reason(name) or "UNCLASSIFIED"
                print(f"{rel}:{number}: {name}: {reason}")
            elif process_global_reason(name) is None:
                unknown.append(f"{rel}:{number}: {text}")
        if args.mode == "guard" and new_text is not None:
            with open(path, "wb") as f:
                f.write(new_text.encode("latin-1"))
            changed += 1

    for line in unknown:
        problems.append(
            f"{line}\n    unclassified singleton: list it in {SINGLETON_LIST} (per engine) or in "
            "PROCESS_GLOBAL in this script (with a reason)"
        )

    if args.mode == "guard":
        print(f"guarded {len(guarded_names)} names in {changed} files")
        if unknown:
            print("\n".join(unknown), file=sys.stderr)
            print(f"{len(unknown)} unclassified `extern ... The*;` lines (see `check`)", file=sys.stderr)
            return 1
        return 0
    if args.mode == "check":
        if problems:
            print("\n".join(problems), file=sys.stderr)
            return 1
        print(f"ok: {len(names)} singletons, macro header current, every extern guarded or classified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
