/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

////////////////////////////////////////////////////////////////////////////////
//																																						//
//  (c) 2001-2003 Electronic Arts Inc.																				//
//																																						//
////////////////////////////////////////////////////////////////////////////////

// FILE: NameKeyGenerator.h ///////////////////////////////////////////////////////////////////////
// Created:    Michael Booth, May 2001
//						 Colin Day, May 2001
// Desc:       Name key system to translate between names and unique key ids
///////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include "Lib/BaseType.h"
#include "Common/SubsystemInterface.h"
#include "Common/GameMemory.h"
#include "Common/AsciiString.h"

#if RTS_ENGINE_CONTEXT
#include <atomic>
#include <mutex>
#endif

//-------------------------------------------------------------------------------------------------
// Note that NameKeyType isn't a "real" enum, but an enum type used to enforce the
// fact that NameKeys are really magic cookies, and aren't really interchangeable
// with integers. NAMEKEY_INVALID is always a legal value, but all other values are dynamically
// determined at runtime. (The generated code is basically identical, of course.)
//-------------------------------------------------------------------------------------------------
enum NameKeyType CPP_11(: Int)
{
	NAMEKEY_INVALID					= 0,
	NAMEKEY_MAX							= 1<<23, // max ordinal value of a NameKey (some code relies on these fitting into 24 bits safely)
	FORCE_NAMEKEYTYPE_LONG	= 0x7fffffff, // a trick to ensure the NameKeyType is a 32-bit int
};

//-------------------------------------------------------------------------------------------------
// A bucket entry for the name key generator
//-------------------------------------------------------------------------------------------------
class Bucket : public MemoryPoolObject
{

	MEMORY_POOL_GLUE_WITH_USERLOOKUP_CREATE( Bucket, "NameKeyBucketPool" );

public:

	Bucket();
//~Bucket();

	Bucket				*m_nextInSocket;
	NameKeyType		m_key;
	AsciiString		m_nameString;
};

inline Bucket::Bucket() : m_nextInSocket(nullptr), m_key(NAMEKEY_INVALID) { }
inline Bucket::~Bucket() { }

//-------------------------------------------------------------------------------------------------
// This class implements the conversion of an arbitrary string into a unique
// integer "key". Calling the nameToKey() method with the same string is
// guaranteed to return the same key. Also, all keys generated by an
// instance of this class are guaranteed to be unique with respect to that
// instance's catalog of names. Multiple instances of this class can be
// created to service multiple namespaces.
//-------------------------------------------------------------------------------------------------
class NameKeyGenerator : public SubsystemInterface
{

public:

	NameKeyGenerator();
	virtual ~NameKeyGenerator() override;

	virtual void init() override;
	virtual void reset() override;
	virtual void update() override { }

	/// Given a string, convert into a unique integer key.
	NameKeyType nameToKey(const AsciiString& name);
	NameKeyType nameToLowercaseKey(const AsciiString& name);

	/// Given a string, convert into a unique integer key.
	NameKeyType nameToKey(const char* name);
	NameKeyType nameToLowercaseKey(const char *name);

	// given a key, return the name. this is almost never needed,
	// except for a few rare cases like object serialization. also
	// note that it's not particularly fast; it does a dumb linear
	// search for the key.
	AsciiString keyToName(NameKeyType key);

	// Get a string out of the INI. Store it into a NameKeyType
	static void parseStringAsNameKeyType( INI *ini, void *instance, void *store, const void* userData );

	// GeneralsX @feature cemlyn007 28/09/2026 Test hook for PLAN-023 Decision 2's perturbation gate:
	// interns `junkNames` names no data uses, then skips `skippedIds` ids, so every key interned
	// afterwards differs from an unperturbed run. With `descending`, the generator also switches, for
	// good, to handing out every later key from the top of the key space downwards, so keys interned
	// afterwards also come in the reverse of their interning order (with several engines sharing the
	// generator, an engine finds keys another interned in that engine's order). The simulation must
	// notice neither. Returns FALSE, changing nothing, if that would leave fewer than
	// NAMEKEY_PERTURB_RESERVE keys free below NAMEKEY_MAX. Never call it in play.
	Bool perturbForTesting(Int junkNames, Int skippedIds, Bool descending);
	enum { NAMEKEY_PERTURB_RESERVE = 1 << 20 };

#if RETAIL_COMPATIBLE_CRC
#if RTS_ZEROHOUR
	void syncNameKeyID();
#endif
	void verifyNameKeyID(UnsignedInt expectedNextID) const;
#endif

#if RTS_ENGINE_CONTEXT
	// GeneralsX @feature cemlyn007 28/09/2026 The shared, immortal generator (PLAN-023 Decision 2).
	// With several engines in one process there is one generator for all of them, never deleted:
	// about 1,250 function-local and file statics cache keys, and those outlive every engine. It is
	// thread-safe: lookups read the bucket chains lock-free (atomic heads, buckets immutable once
	// published), inserts take a mutex, and keyToName returns a copy of the name.
	//
	// Priming: the first engine in the process (the priming engine) makes the generator and runs
	// GameEngine::init alone. Every later engine boots from the same data, so it finds every boot
	// name already interned, with the same key, and must intern nothing new until its upgrades are
	// loaded (the science and upgrade keys are what orders carry): a new name there means different
	// data, which is a fatal error. If the priming engine fails partway, the generator holds a
	// partial prefix that a retry would extend differently, so the process is poisoned: every later
	// engine fails in GameEngine::init, and the host has to restart the process.
	enum PrimingState
	{
		PRIMING_NOT_STARTED,	///< no engine has started GameEngine::init in this process
		PRIMING_IN_PROGRESS,	///< the priming engine is inside GameEngine::init
		PRIMED,								///< the priming engine completed GameEngine::init
		PRIMING_FAILED,				///< the priming engine failed: no engine can boot in this process
	};
	static PrimingState getPrimingState();

	// Held by GameEngine::init for its whole run. The constructor makes the generator if this is the
	// priming engine (or fails if another engine is priming, or priming failed); complete() at the
	// end of a successful init; destroyed without complete(), a priming engine poisons the process.
	class PrimingLatch
	{
	public:
		PrimingLatch();
		~PrimingLatch();
		// This engine may intern new names from here on (its upgrades are loaded).
		void endFrozenNames();
		void complete();

	private:
		PrimingLatch(const PrimingLatch&);
		PrimingLatch& operator=(const PrimingLatch&);

		Bool m_priming;
		Bool m_completed;
	};
#endif

private:

	enum
	{
		// socketcount should be prime, and not "close" to a power of 2, for best results.
		SOCKET_COUNT = 45007
	};

	NameKeyType createNameKey(UnsignedInt hash, const AsciiString& name);

	void freeSockets();

#if RTS_ENGINE_CONTEXT
	// GeneralsX @feature cemlyn007 28/09/2026 Thread-safe with several engines (see PrimingLatch)
	std::atomic<Bucket*>	m_sockets[SOCKET_COUNT];	///< Catalog of all Buckets already generated; a bucket is immutable once published
	UnsignedInt		m_nextID;											///< Next available ID; guarded by m_insertMutex
	UnsignedInt		m_descendingID;								///< Next ID handed out downwards, or 0 (perturbForTesting); guarded by m_insertMutex
	std::mutex		m_insertMutex;								///< Held by every insert
#else
	Bucket*				m_sockets[SOCKET_COUNT];			///< Catalog of all Buckets already generated
	UnsignedInt		m_nextID;											///< Next available ID
	UnsignedInt		m_descendingID;								///< GeneralsX @feature cemlyn007 28/09/2026 Next ID handed out downwards, or 0 (perturbForTesting)
#endif

};

//-------------------------------------------------------------------------------------------------
//           Externals
//-------------------------------------------------------------------------------------------------
extern NameKeyGenerator *TheNameKeyGenerator;  ///< just one namespace for now

// typing "TheNameKeyGenerator->nameToKey()" is awfully wordy. Here are shorter synonyms:
inline NameKeyType NAMEKEY(const AsciiString& name) { return TheNameKeyGenerator->nameToKey(name); }
inline NameKeyType NAMEKEY(const char* name) { return TheNameKeyGenerator->nameToKey(name); }

inline AsciiString KEYNAME(NameKeyType nk) { return TheNameKeyGenerator->keyToName(nk); }

//-------------------------------------------------------------------------------------------------
class StaticNameKey
{
private:
#if RTS_ENGINE_CONTEXT
	// GeneralsX @feature cemlyn007 28/09/2026 Written lazily by whichever engine reads it first
	mutable std::atomic<NameKeyType> m_key;
#else
	mutable NameKeyType m_key;
#endif
	const char* m_name;
public:
	StaticNameKey(const char* p) : m_key(NAMEKEY_INVALID), m_name(p) {}
	NameKeyType key() const;
	// ugh, this is a little hokey, but lets us pretend that a StaticNameKey == NameKeyType
	operator NameKeyType() const { return key(); }
};
